<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="ChartData">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="labels" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="datasets">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="dataset" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="label" type="xs:string"/>
                                        <xs:element name="data" type="xs:float" minOccurs="0" maxOccurs="unbounded"/>
                                        <xs:element name="backgroundColor" type="xs:string" minOccurs="0"/>
                                        <xs:element name="borderColor" type="xs:string" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
