/****** Object: Table [dbo].[DFADJCONTENIDO]   Script Date: 30-08-2025 18:36:38 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFADJCONTENIDO] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[DFTipo] nvarchar(1) NOT NULL,
[DFAno] smallint NOT NULL,
[DFMes] smallint NOT NULL,
[DFCor] int NOT NULL,
[ID_CONTENIDO] smallint NOT NULL,
[ContenidoPdf] varbinary(MAX) NULL,
[DFADJCONFIRMA] nvarchar(128) NOT NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFADJCONTENIDO] SET (LOCK_ESCALATION = TABLE);
GO
