/****** Object: Table [dbo].[DFASIGNAR]   Script Date: 30-08-2025 18:36:45 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFASIGNAR] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[DFTipo] nvarchar(1) NOT NULL,
[DFAno] smallint NOT NULL,
[DFMes] smallint NOT NULL,
[DFCor] int NOT NULL,
[DFOCUR] smallint NOT NULL,
[DFASIGNARUSURESPONSABLE] nvarchar(20) NOT NULL,
[DFASIGNARUSUAUTO] nvarchar(20) NOT NULL,
[DFASIGNARNIVAUTO] nvarchar(20) NOT NULL,
[DFASIGNARNIVRESPONSABLE] nvarchar(20) NOT NULL,
[DFASIGNARFECHAREGISTRO] datetime NOT NULL,
[DFASIGNARACCION] smallint NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFASIGNAR] SET (LOCK_ESCALATION = TABLE);
GO
