/****** Object: Table [dbo].[DFAVIDETAL]   Script Date: 30-08-2025 18:36:44 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFAVIDETAL] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[NivCod] nvarchar(20) NOT NULL,
[USUCOD] nvarchar(25) NOT NULL,
[ANOAVISO] smallint NOT NULL,
[MESAVISO] smallint NOT NULL,
[NAVISO] int NOT NULL,
[NAVIDETALLE] int NOT NULL,
[AVIDETFECHA] datetime NULL,
[AVIDETESTADO] smallint NOT NULL,
[AVIDETHORA] nvarchar(8) NULL,
[AVIDETACTIVAR] smallint NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFAVIDETAL] SET (LOCK_ESCALATION = TABLE);
GO
