/****** Object: Table [dbo].[DFAVISO]   Script Date: 30-08-2025 18:36:44 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFAVISO] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[ANOAVISO] smallint NOT NULL,
[MESAVISO] smallint NOT NULL,
[NAVISO] int NOT NULL,
[AVIPRIORIDAD] smallint NOT NULL,
[AVIASUNTO] nvarchar(250) NULL,
[NIVCODORI] nvarchar(20) NULL,
[USUCODORI] nvarchar(25) NULL,
[AVITEXTO] nvarchar(MAX) NULL,
[AVIFECHA] datetime NOT NULL,
[AVIHORA] nvarchar(8) NOT NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFAVISO] SET (LOCK_ESCALATION = TABLE);
GO
