/****** Object: Table [dbo].[DFAYUDAS]   Script Date: 30-08-2025 18:36:44 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFAYUDAS] (
[AyuCod] nvarchar(30) NOT NULL,
[AYUDESC] nvarchar(MAX) NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFAYUDAS] SET (LOCK_ESCALATION = TABLE);
GO
