/****** Object: Table [dbo].[DFCATEGORIA_OLD]   Script Date: 30-08-2025 18:36:48 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFCATEGORIA_OLD] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[DFTipo] nvarchar(1) NOT NULL,
[DFAno] smallint NOT NULL,
[DFMes] smallint NOT NULL,
[DFCor] int NOT NULL,
[DFOCUR] smallint NOT NULL,
[IDCATEGORIA] smallint NOT NULL,
[IDSUBCATEGORIA] smallint NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFCATEGORIA_OLD] SET (LOCK_ESCALATION = TABLE);
GO
