/****** Object: Table [dbo].[DFCONTENIDO]   Script Date: 30-08-2025 18:36:49 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFCONTENIDO] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[DFTipo] nvarchar(1) NOT NULL,
[DFAno] smallint NOT NULL,
[DFMes] smallint NOT NULL,
[DFCor] int NOT NULL,
[DFCONVERSION] smallint NOT NULL,
[DFCONARCHIVO] varbinary(MAX) NOT NULL,
[DFCONEXT] nvarchar(10) NULL,
[DFCONAUTOR] nvarchar(40) NOT NULL,
[DFCONNIVELAUTOR] nvarchar(40) NOT NULL,
[DFCONFECHA] datetime NOT NULL,
[DFCONHORA] nvarchar(8) NOT NULL,
[DFCONAUTO] smallint NULL,
[DFUSUAUTORIZACI] nvarchar(40) NULL,
[DFUSUFIRMADOR] nvarchar(40) NULL,
[DFCONESTADO] nvarchar(1) NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFCONTENIDO] SET (LOCK_ESCALATION = TABLE);
GO
