/****** Object: Table [dbo].[DFCONAUTORIZADO]   Script Date: 30-08-2025 18:36:49 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFCONAUTORIZADO] (
[GUID_AUTORIZADO] uniqueidentifier NOT NULL,
[GUID_DOC] uniqueidentifier NOT NULL,
[USUCOD] nvarchar(20) NOT NULL,
[DFCONVERSION] smallint NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFCONAUTORIZADO] SET (LOCK_ESCALATION = TABLE);
GO
