/****** Object: Table [dbo].[DFCODBAR]   Script Date: 30-08-2025 18:36:49 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFCODBAR] (
[ID_COD] smallint IDENTITY(1, 1) NOT NULL,
[CodBarra] char(500) NOT NULL,
[ORGDEPCOD] char(20) NOT NULL,
[DFTIPO] char(1) NOT NULL,
[DFANO] smallint NOT NULL,
[DFMES] smallint NOT NULL,
[DFCOR] int NOT NULL,
[SINCODBAR] smallint NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFCODBAR] SET (LOCK_ESCALATION = TABLE);
GO
