/****** Object: Table [dbo].[DFDOCDIGITALANEXOS]   Script Date: 30-08-2025 18:36:52 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFDOCDIGITALANEXOS] (
[DFDOCDIGITALANEXOSID] int NOT NULL,
[DFDOCDIGITALANEXOSNOMBRE] nvarchar(1000) NOT NULL,
[DFDOCDIGITALANEXOSURL] nvarchar(1000) NULL,
[DFDOCDIGITALANEXOSTIPO] nvarchar(40) NULL,
[DFDOCDIGITALANEXOSARCHIVO] nvarchar(MAX) NULL,
[DOCDIGITALID] int NOT NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFDOCDIGITALANEXOS] SET (LOCK_ESCALATION = TABLE);
GO
