/****** Object: Table [dbo].[DFDOCUMDOCDIGITAL]   Script Date: 30-08-2025 18:36:57 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFDOCUMDOCDIGITAL] (
[DOCDIGITALID] int NOT NULL,
[DOCDIGITALDFFCHORIG] datetime NULL,
[DOCDIGITALDFObjetivo] nvarchar(2000) NULL,
[DOCDIGITALDFORICod] nvarchar(40) NULL,
[DOCDIGITALDFDocNro] nvarchar(40) NULL,
[DOCDIGITALDFPRIOR] nvarchar(1) NULL,
[DOCDIGITALtipo_cod] int NULL,
[DOCDIGITALARCHIVO] nvarchar(MAX) NULL,
[DOCDIGITALJSON] nvarchar(MAX) NULL,
[DOCDIGITALESTADO] int NULL,
[DFDOCUMDOCDIGITALORGDEPCOD] nvarchar(20) NULL,
[DFDOCUMDOCDIGITALDFTIPO] nvarchar(1) NULL,
[DFDOCUMDOCDIGITALDFANO] smallint NULL,
[DFDOCUMDOCDIGITALDFMES] smallint NULL,
[DFDOCUMDOCDIGITALDFCOR] int NULL,
[DOCDIGITALdfclasif] int NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFDOCUMDOCDIGITAL] SET (LOCK_ESCALATION = TABLE);
GO
