/****** Object: Table [dbo].[DFEDIFIC]   Script Date: 30-08-2025 18:36:59 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFEDIFIC] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[DFEDIFCOD] nvarchar(25) NOT NULL,
[DFEDIFOFIC] nvarchar(25) NOT NULL,
[DFEDIFEST] nvarchar(25) NOT NULL,
[DFEDIFDIRE] nvarchar(25) NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFEDIFIC] SET (LOCK_ESCALATION = TABLE);
GO
