/****** Object: Table [dbo].[DFENVIO_EMAIL]   Script Date: 30-08-2025 18:37:03 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFENVIO_EMAIL] (
[MID] int IDENTITY(1, 1) NOT NULL,
[MCARPETA] char(250) NULL,
[MCCOPIA] char(250) NULL,
[MMAL] varchar(MAX) NULL,
[MNOMBRE] char(250) NULL,
[MHORA] char(8) NULL,
[MCORREO] char(250) NULL,
[MADJ] smallint NULL,
[MCTEXTO] varchar(MAX) NULL,
[MFEMISION] char(50) NULL,
[MOBJETIVO] varchar(MAX) NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFENVIO_EMAIL] SET (LOCK_ESCALATION = TABLE);
GO
