/****** Object: Table [dbo].[DFESTADODOC]   Script Date: 30-08-2025 18:37:04 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFESTADODOC] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[DFTIPO] nvarchar(8) NOT NULL,
[COD_DFESTADO] int NOT NULL,
[DESC_DFESTADO] nvarchar(60) NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFESTADODOC] SET (LOCK_ESCALATION = TABLE);
GO
