/****** Object: Table [dbo].[DFOBING]   Script Date: 30-08-2025 18:37:27 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFOBING] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[DFTipo] nvarchar(1) NOT NULL,
[DFAno] smallint NOT NULL,
[DFMes] smallint NOT NULL,
[DFCor] int NOT NULL,
[DFOCUR] smallint NOT NULL,
[DFOBNRO] smallint NOT NULL,
[DFOBFCH] datetime NULL,
[DFOBSERV] nvarchar(MAX) NULL,
[DFOBHRS] nvarchar(8) NULL,
[USUCOD] nvarchar(25) NOT NULL,
[DFOBENCAB] nvarchar(50) NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFOBING] SET (LOCK_ESCALATION = TABLE);
GO
