/****** Object: Table [dbo].[DFOPNOTIFICADOR]   Script Date: 30-08-2025 18:37:29 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFOPNOTIFICADOR] (
[CODOPCION] smallint NOT NULL,
[ACCION] nvarchar(50) NOT NULL,
[GLOSAACCION] nvarchar(500) NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFOPNOTIFICADOR] SET (LOCK_ESCALATION = TABLE);
GO
