/****** Object: Table [dbo].[DFRESPUESTAZONA]   Script Date: 30-08-2025 18:37:31 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFRESPUESTAZONA] (
[NRESP] int NOT NULL,
[NLineas] int NOT NULL,
[RESP] char(80) NOT NULL,
[FCHRESP] datetime NOT NULL,
[HORARESP] char(8) NOT NULL,
[RESPNIV] char(20) NOT NULL,
[RESPUSU] char(25) NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFRESPUESTAZONA] SET (LOCK_ESCALATION = TABLE);
GO
