/****** Object: Table [dbo].[DFRESTAR]   Script Date: 30-08-2025 18:37:35 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFRESTAR] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[TARANOTARE] smallint NOT NULL,
[TARNIVRESP] nvarchar(20) NOT NULL,
[TARNIVAUTO] nvarchar(20) NOT NULL,
[TARUSUAUTO] nvarchar(25) NOT NULL,
[TARNRO] int NOT NULL,
[RESNRO] int NOT NULL,
[RESFCHING] datetime NULL,
[RESNIVING] nvarchar(20) NULL,
[RESUSUING] nvarchar(25) NULL,
[RESRESPUES] nvarchar(80) NULL,
[RESOBSERV] nvarchar(MAX) NULL,
[RESFCHRESP] datetime NULL,
[RESNROHRS] smallint NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFRESTAR] SET (LOCK_ESCALATION = TABLE);
GO
