/****** Object: Table [dbo].[DFRESPUETAZONAL]   Script Date: 30-08-2025 18:37:32 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFRESPUETAZONAL] (
[NRESP] int NOT NULL,
[NLineas] int NOT NULL,
[RESP] nvarchar(80) NOT NULL,
[FCHRESP] datetime NOT NULL,
[HORARESP] nvarchar(8) NOT NULL,
[RESPNIV] nvarchar(40) NOT NULL,
[RESPUSU] nvarchar(40) NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFRESPUETAZONAL] SET (LOCK_ESCALATION = TABLE);
GO
