/****** Object: Table [dbo].[DFSESION]   Script Date: 30-08-2025 18:37:37 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFSESION] (
[SEORGDEPCOD] nvarchar(40) NOT NULL,
[SEUSUCOD] nvarchar(25) NOT NULL,
[SENIVCOD] nvarchar(40) NOT NULL,
[ID_SESION_WEB] nvarchar(100) NOT NULL,
[DFSEFECHA] datetime NOT NULL,
[DFSEHORA] nvarchar(8) NOT NULL,
[SEIP] varchar(40) NULL,
[SEACTIVO] int NULL,
[SESISCOD] int NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFSESION] SET (LOCK_ESCALATION = TABLE);
GO
