/****** Object: Table [dbo].[DFTAREASDOC]   Script Date: 30-08-2025 18:37:42 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFTAREASDOC] (
[DFTAREASDOCFECHAINICIO] datetime NOT NULL,
[DFTAREASDOCFECHATERMINO] datetime NOT NULL,
[DFTAREASDOCFECHAINGRESO] datetime NOT NULL,
[DFTAREASDOCHORAINGRESO] datetime NOT NULL,
[DFTAREASDOCID] int IDENTITY(1, 1) NOT NULL,
[DFTAREASDOCIDPADRE] int NULL,
[DFCor] int NOT NULL,
[DFTipo] nvarchar(1) NOT NULL,
[DFTAREASDOCOBSERV] nvarchar(1000) NULL,
[ORGDEPCOD] nvarchar(20) NOT NULL,
[DFTAREASDOCNIVAUTO] nvarchar(20) NOT NULL,
[DFTAREASDOCNIVRESP] nvarchar(20) NOT NULL,
[DFTAREASDOCUSUAUTO] nvarchar(25) NOT NULL,
[DFTAREASDOCUSURESP] nvarchar(25) NOT NULL,
[DFTACCION] nvarchar(30) NOT NULL,
[DFTAREASDOCRESUMEN] nvarchar(500) NULL,
[DFAno] smallint NOT NULL,
[DFMes] smallint NOT NULL,
[DFOCUR] smallint NOT NULL,
[DFTAREASDOCESTADO] smallint NOT NULL,
[DFTAREASDOCPRIORIDAD] smallint NOT NULL,
[DFTAREASDOCRESPCONDOC] smallint NOT NULL,
[DFTAREASDOCFECHAACEPTADA] datetime NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFTAREASDOC] SET (LOCK_ESCALATION = TABLE);
GO
