/****** Object: Table [dbo].[DFTEXTO]   Script Date: 30-08-2025 18:37:43 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFTEXTO] (
[ORGDEPCOD] char(20) NOT NULL,
[DFTIPO] char(1) NOT NULL,
[DFANO] smallint NOT NULL,
[DFMES] smallint NOT NULL,
[DFCOR] int NOT NULL,
[DFTXTVERSION] smallint NOT NULL,
[DFTXTARCHIVO] text NOT NULL,
[DFTXTAUTOR] char(20) NOT NULL,
[DFTXTNIVCODAUTO] char(20) NOT NULL,
[DFTXTFECHA] datetime NOT NULL,
[DFTXTHORA] char(8) NOT NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFTEXTO] SET (LOCK_ESCALATION = TABLE);
GO
