/****** Object: Table [dbo].[DFUSUAUTORIZADOS]   Script Date: 30-08-2025 18:37:41 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[DFUSUAUTORIZADOS] (
[ORGDEPCOD] varchar(20) NOT NULL,
[DFTipo] varchar(1) NOT NULL,
[DFAno] smallint NOT NULL,
[DFMes] smallint NOT NULL,
[DFCor] int NOT NULL,
[DFUSUAUTPOS] smallint NOT NULL,
[DFUSUAUTSIGLA] char(50) NOT NULL,
[USUCOD] varchar(25) NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[DFUSUAUTORIZADOS] SET (LOCK_ESCALATION = TABLE);
GO
