/****** Object: Table [dbo].[EDN_FARO]   Script Date: 30-08-2025 18:37:45 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[EDN_FARO] (
[ID_FARO] int IDENTITY(1, 1) NOT FOR REPLICATION NOT NULL,
[ID_MENSAJE] int NOT NULL,
[SIGLA] varchar(20) NOT NULL,
[ORDEN] smallint NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[EDN_FARO] SET (LOCK_ESCALATION = TABLE);
GO
