/****** Object: Table [dbo].[EDN_PREFIJO]   Script Date: 30-08-2025 18:37:45 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[EDN_PREFIJO] (
[ID_PREFIJO] smallint IDENTITY(1, 1) NOT FOR REPLICATION NOT NULL,
[DESCRIPCION] varchar(20) NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[EDN_PREFIJO] SET (LOCK_ESCALATION = TABLE);
GO
