/****** Object: Table [dbo].[EDN_MENSAJE]   Script Date: 30-08-2025 18:37:45 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[EDN_MENSAJE] (
[ID_MENSAJE] int IDENTITY(1, 1) NOT FOR REPLICATION NOT NULL,
[NUMERO] char(15) NOT NULL,
[TITULO] varchar(100) NOT NULL,
[CUERPO] varchar(MAX) NOT NULL,
[DOCUMENTO] image NULL,
[ID_TIPO] smallint NOT NULL,
[ID_CLASIFICACION] smallint NOT NULL,
[ID_PREFIJO] smallint NOT NULL,
[ID_ORIGINADOR] smallint NOT NULL,
[USUARIO] varchar(20) NOT NULL,
[FECHA_CREACION] datetime NULL,
[FECHA_ACTUALIZACION] datetime NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[EDN_MENSAJE] SET (LOCK_ESCALATION = TABLE);
GO
