/****** Object: Table [dbo].[F_DOC]   Script Date: 30-08-2025 18:37:54 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[F_DOC] (
[IDF_DOC] smallint NOT NULL,
[ORGDEPCOD_TMP] nvarchar(40) NOT NULL,
[NIVCOD_TMP] nvarchar(40) NOT NULL,
[DFTIPO_TMP] nvarchar(1) NOT NULL,
[DFANO_TMP] smallint NOT NULL,
[DFMES_TMP] smallint NOT NULL,
[DFCOR_TMP] int NOT NULL,
[USUCOD_TMP] nvarchar(25) NOT NULL,
[FCHENVIAFIRMA_TMP] datetime NOT NULL,
[NOMBREADJ_TMP] nvarchar(250) NOT NULL,
[EXT_TMP] nvarchar(40) NOT NULL,
[ARCHIVO_TMP] varbinary(MAX) NOT NULL,
[ESTADO_TMP] nvarchar(1) NOT NULL,
[DFDOCNRO_TMP] nvarchar(40) NOT NULL,
[HORA_TMP] nvarchar(8) NOT NULL,
[FCHFIRMA_TMP] datetime NULL,
[NOMBREUSU_TMP] nvarchar(80) NOT NULL,
[NIVDESC_TMP] nvarchar(60) NOT NULL,
[OBSERRECHA_TMP] nvarchar(200) NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[F_DOC] SET (LOCK_ESCALATION = TABLE);
GO
