/****** Object: Table [dbo].[FACTURASTMP]   Script Date: 30-08-2025 18:37:54 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[FACTURASTMP] (
[ORGDEPCOD] char(20) NOT NULL,
[DFTIPO] char(1) NOT NULL,
[DFANO] smallint NOT NULL,
[DFMES] smallint NOT NULL,
[DFCOR] int NOT NULL,
[FACNUMFOLIO] varchar(40) NOT NULL,
[FACXML] varchar(250) NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[FACTURASTMP] SET (LOCK_ESCALATION = TABLE);
GO
