/****** Object: Table [dbo].[SECATEGORIAS]   Script Date: 30-08-2025 18:37:57 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[SECATEGORIAS] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[IDCATEGORIA] smallint NOT NULL,
[CATENOMBRE] nvarchar(200) NOT NULL,
[CATEDESCRIPCION] nvarchar(200) NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[SECATEGORIAS] SET (LOCK_ESCALATION = TABLE);
GO
