/****** Object: Table [dbo].[SECATALO]   Script Date: 30-08-2025 18:37:57 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[SECATALO] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[CATCOD] int NOT NULL,
[CATDESC] nvarchar(60) NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[SECATALO] SET (LOCK_ESCALATION = TABLE);
GO
