/****** Object: Table [dbo].[SECORFOR]   Script Date: 30-08-2025 18:38:01 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[SECORFOR] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[CORRTIP] nvarchar(8) NOT NULL,
[CORRNRO] int NOT NULL,
[CORRDES] nvarchar(60) NOT NULL,
[CORRFCH] datetime NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[SECORFOR] SET (LOCK_ESCALATION = TABLE);
GO
