/****** Object: Table [dbo].[SECORFORDOCTIPNIV]   Script Date: 30-08-2025 18:38:02 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[SECORFORDOCTIPNIV] (
[ORGDEPCODTIPNIV] nvarchar(20) NOT NULL,
[DFTipoTIPNIV] nvarchar(1) NOT NULL,
[TIPOCODTIPNIV] smallint NOT NULL,
[NivCodTIPNIV] nvarchar(20) NOT NULL,
[FECHATIPNIV] datetime NOT NULL,
[CONTADORTIPNIV] int NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[SECORFORDOCTIPNIV] SET (LOCK_ESCALATION = TABLE);
GO
