/****** Object: Table [dbo].[SEDEFIMP]   Script Date: 30-08-2025 18:38:07 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[SEDEFIMP] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[ANCHO_ETIQUETA] smallint NOT NULL,
[IMPRESORA] nvarchar(102) NULL,
[MARGEN_IZQUIERD] smallint NULL,
[ALTO_ETIQUETA] smallint NULL,
[FUENTE_SUBRAYAD] nvarchar(1) NULL,
[ALTO_PAPEL] smallint NULL,
[SALTO_INFERERIO] smallint NULL,
[FUENTE_BOLD] nvarchar(1) NULL,
[SALTO_LATERAL] smallint NULL,
[FUENTE_TACHADO] nvarchar(1) NULL,
[FUENTE_ITALICO] nvarchar(1) NULL,
[MARGEN_INFERIOR] smallint NULL,
[MARGEN_DERECHO] smallint NULL,
[FUENTE] nvarchar(50) NULL,
[MARGEN_SUPERIOR] smallint NULL,
[ANCHO_PAPEL] smallint NULL,
[FUENTE_TAMANO] smallint NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[SEDEFIMP] SET (LOCK_ESCALATION = TABLE);
GO
