/****** Object: Table [dbo].[SEEMAIL]   Script Date: 30-08-2025 18:38:10 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[SEEMAIL] (
[ORGDEPCOD] char(20) NOT NULL,
[EMEVENTO] smallint NOT NULL,
[EMNOMBRE] char(100) NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[SEEMAIL] SET (LOCK_ESCALATION = TABLE);
GO
