/****** Object: Table [dbo].[SEFORDOC]   Script Date: 30-08-2025 18:38:14 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[SEFORDOC] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[tipo_cod] smallint NOT NULL,
[TIPO_REC] int NOT NULL,
[TIPO_INT] int NOT NULL,
[tipo_desc] nvarchar(100) NOT NULL,
[CORRN] int NOT NULL,
[CORRFECHA] datetime NOT NULL,
[TIPO_ENV] int NOT NULL,
[SEFORDOCVISTAI] smallint NOT NULL,
[SEFORDOCVISTAE] smallint NOT NULL,
[SEFORDOCVISTAR] smallint NOT NULL,
[SEFORDOCFORMATONUM] nvarchar(40) NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[SEFORDOC] SET (LOCK_ESCALATION = TABLE);
GO
