/****** Object: Table [dbo].[SEFORDOCNIV]   Script Date: 30-08-2025 18:38:10 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[SEFORDOCNIV] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[NivCod] nvarchar(20) NOT NULL,
[tipo_cod] smallint NOT NULL,
[CORRELATIVO] int NOT NULL,
[FECHACORRE] datetime NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[SEFORDOCNIV] SET (LOCK_ESCALATION = TABLE);
GO
