/****** Object: Table [dbo].[SEFORPLAMEDIDAS]   Script Date: 30-08-2025 18:38:21 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[SEFORPLAMEDIDAS] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[codform] nvarchar(100) NOT NULL,
[IDFORPLAMED] smallint NOT NULL,
[FORPLAMEDOBJETO] nvarchar(40) NOT NULL,
[FORPLAMEDX] smallint NOT NULL,
[FORPLAMEDY] smallint NOT NULL,
[FORPLAMEDANCHO] smallint NOT NULL,
[FORPLAMEDALTO] smallint NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[SEFORPLAMEDIDAS] SET (LOCK_ESCALATION = TABLE);
GO
