/****** Object: Table [dbo].[SEFORSII]   Script Date: 30-08-2025 18:38:22 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[SEFORSII] (
[TIPO_DTE] smallint NOT NULL,
[DESCTIPODTE] nvarchar(150) NOT NULL,
[DESCMINTIPODTE] nvarchar(150) NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[SEFORSII] SET (LOCK_ESCALATION = TABLE);
GO
