/****** Object: Table [dbo].[SEFORDOCSII]   Script Date: 30-08-2025 18:38:17 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[SEFORDOCSII] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[tipo_cod] smallint NOT NULL,
[DFTIPOSII] smallint NOT NULL,
[DFDESCSII] nvarchar(60) NULL,
[DFTIPOARCHIVOSII] nvarchar(40) NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[SEFORDOCSII] SET (LOCK_ESCALATION = TABLE);
GO
