/****** Object: Table [dbo].[SEFORPLAHTML]   Script Date: 30-08-2025 18:38:21 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[SEFORPLAHTML] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[IDPLAHTML] nvarchar(40) NOT NULL,
[DESCPLANTILLA] nvarchar(100) NULL,
[ARCHIVOHTML] nvarchar(MAX) NOT NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[SEFORPLAHTML] SET (LOCK_ESCALATION = TABLE);
GO
