/****** Object: Table [dbo].[SELOG]   Script Date: 30-08-2025 18:38:26 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[SELOG] (
[SELOGID] decimal(12, 0) IDENTITY(1, 1) NOT NULL,
[SELOGUSURIO] nvarchar(20) NULL,
[SELOGNIVEL] nvarchar(20) NULL,
[SELOGORGDEPCOD] nvarchar(20) NULL,
[SELOGFECHAHORA] datetime NULL,
[SELOGTIPO] nvarchar(30) NULL,
[SELOGDETALLE] nvarchar(MAX) NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[SELOG] SET (LOCK_ESCALATION = TABLE);
GO
