/****** Object: Table [dbo].[SEORGDEP]   Script Date: 30-08-2025 18:38:28 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[SEORGDEP] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[ORGSUPCOD] nvarchar(20) NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[SEORGDEP] SET (LOCK_ESCALATION = TABLE);
GO
