/****** Object: Table [dbo].[SEREMTIP]   Script Date: 30-08-2025 18:38:33 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[SEREMTIP] (
[REMTIPO] nvarchar(3) NOT NULL,
[REMDESC] nvarchar(30) NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[SEREMTIP] SET (LOCK_ESCALATION = TABLE);
GO
