/****** Object: Table [dbo].[SERESNUM]   Script Date: 30-08-2025 18:38:31 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[SERESNUM] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[TIPO] smallint NOT NULL,
[NUMRESER] int NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[SERESNUM] SET (LOCK_ESCALATION = TABLE);
GO
