/****** Object: Table [dbo].[SESUBCATEGORIAS]   Script Date: 30-08-2025 18:38:34 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[SESUBCATEGORIAS] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[CATCOD] smallint NOT NULL,
[IDSUBCATEGORIA] smallint NOT NULL,
[SUBCATENOMBRE] nvarchar(200) NOT NULL,
[SUBCATEDESCRIPCION] nvarchar(200) NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[SESUBCATEGORIAS] SET (LOCK_ESCALATION = TABLE);
GO
