/****** Object: Table [dbo].[SETIPTAR]   Script Date: 30-08-2025 18:38:35 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[SETIPTAR] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[DFTACCION] nvarchar(30) NOT NULL,
[DFTACOBSV] nvarchar(MAX) NULL,
[DFTACDESC] nvarchar(60) NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[SETIPTAR] SET (LOCK_ESCALATION = TABLE);
GO
