/****** Object: Table [dbo].[SEUSUFIRMA]   Script Date: 30-08-2025 18:38:35 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[SEUSUFIRMA] (
[GUID_USU] uniqueidentifier NOT NULL,
[USUCOD] nvarchar(20) NOT NULL,
[FIRMA_PNG] varbinary(MAX) NULL,
[MOSCA_PNG] varbinary(MAX) NULL,
[claUsuFirma] int NULL,
[usuSigla] varchar(10) NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[SEUSUFIRMA] SET (LOCK_ESCALATION = TABLE);
GO
