/****** Object: Table [dbo].[SEUSUPERFIL]   Script Date: 30-08-2025 18:38:37 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[SEUSUPERFIL] (
[ORGDEPCOD] char(20) NOT NULL,
[NIVCOD] char(20) NOT NULL,
[USUCOD] char(25) NOT NULL,
[PERFIL] smallint NOT NULL,
[PORDEFECTO] smallint NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[SEUSUPERFIL] SET (LOCK_ESCALATION = TABLE);
GO
