/****** Object: Table [dbo].[SEUSUARI]   Script Date: 30-08-2025 18:38:36 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[SEUSUARI] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[NivCod] nvarchar(20) NOT NULL,
[USUCOD] nvarchar(25) NOT NULL,
[DESCCARGO] nvarchar(150) NULL,
[USUCODACTIVOSUBRO] bit NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[SEUSUARI] SET (LOCK_ESCALATION = TABLE);
GO
