/****** Object: Table [dbo].[SEUSUFIRMADOR]   Script Date: 30-08-2025 18:38:35 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[SEUSUFIRMADOR] (
[IDUSUFIR] uniqueidentifier ROWGUIDCOL NOT NULL,
[USUCODFIRMADOR] varchar(25) NOT NULL,
[USUFIRFIRMA] varbinary(MAX) NULL,
[USUFIRCLAVE] char(512) NOT NULL,
[USUFIRSIGLA] char(50) NOT NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[SEUSUFIRMADOR] SET (LOCK_ESCALATION = TABLE);
GO
