/****** Object: Table [dbo].[TMPADJUNTOS]   Script Date: 30-08-2025 18:38:41 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[TMPADJUNTOS] (
[TMPIDADJUNTOS] int IDENTITY(1, 1) NOT NULL,
[TMPGUIDADJUNTOS] uniqueidentifier NULL,
[TMPNOMBREADJUNTOS] nvarchar(200) NULL,
[TMPEXTADJUNTOS] nvarchar(10) NULL,
[TMPARCHIVOADJUNTOS] varbinary(MAX) NULL,
[TMPESDOCUMENTO] smallint NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[TMPADJUNTOS] SET (LOCK_ESCALATION = TABLE);
GO
