/****** Object: Table [dbo].[TMPDFSELECCION]   Script Date: 30-08-2025 18:38:39 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[TMPDFSELECCION] (
[DFSELGRID] nvarchar(100) NOT NULL,
[idtemp] smallint NOT NULL,
[ORGDEPCOD] nvarchar(20) NOT NULL,
[NivCod] nvarchar(20) NOT NULL,
[USUCOD] nvarchar(25) NOT NULL,
[DFTipo] nvarchar(1) NOT NULL,
[DFAno] smallint NOT NULL,
[DFMes] smallint NOT NULL,
[DFCor] int NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[TMPDFSELECCION] SET (LOCK_ESCALATION = TABLE);
GO
