/****** Object: Table [dbo].[TMPENVIO]   Script Date: 30-08-2025 18:38:41 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[TMPENVIO] (
[TMPIDENVIO] int IDENTITY(1, 1) NOT NULL,
[TMPGUIDENVIO] uniqueidentifier NULL,
[TMPDFECodNiv] nvarchar(20) NULL,
[TMPUSUCODRESPONSAB] nvarchar(25) NULL,
[TMPENVIOUSUCREADOR] nvarchar(25) NULL,
[TMPENVIONIVCREADOR] nvarchar(20) NULL,
[TMPENVIOTIPO] nvarchar(200) NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[TMPENVIO] SET (LOCK_ESCALATION = TABLE);
GO
