/****** Object: Table [dbo].[TMPOBSERVACION]   Script Date: 30-08-2025 18:38:44 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[TMPOBSERVACION] (
[TMPIDOBSERVACION] int IDENTITY(1, 1) NOT NULL,
[TMPGUIDBSERVACION] uniqueidentifier NULL,
[TMPFECHABSERVACION] datetime NULL,
[TMPHORABSERVACION] nchar(20) NULL,
[TMPNOTABSERVACION] nvarchar(MAX) NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[TMPOBSERVACION] SET (LOCK_ESCALATION = TABLE);
GO
