/****** Object: Table [dbo].[TMPTAREAS]   Script Date: 30-08-2025 18:38:43 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[TMPTAREAS] (
[TMPIDTAREAS] int IDENTITY(1, 1) NOT NULL,
[TMPGUIDTAREAS] uniqueidentifier NULL,
[TMPUSURESTAREAS] nvarchar(20) NULL,
[TMPNIVELRESTAREAS] nvarchar(20) NULL,
[TMPFECHARESPTAREAS] datetime NULL,
[TMPDFACCIONTAREAS] nvarchar(30) NULL,
[TMPRESUMENTAREAS] nvarchar(100) NULL,
[TMPOBSERTAREAS] nvarchar(MAX) NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[TMPTAREAS] SET (LOCK_ESCALATION = TABLE);
GO
