/****** Object: Table [dbo].[VISTADFTAREAScc]   Script Date: 30-08-2025 18:38:45 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[VISTADFTAREAScc] (
[ORGDEPCOD] nvarchar(20) NOT NULL,
[TARANOTARE] smallint NOT NULL,
[TARNIVRESP] nvarchar(20) NOT NULL,
[TARNIVAUTO] nvarchar(20) NOT NULL,
[TARUSUAUTO] nvarchar(25) NOT NULL,
[TARNRO] int NOT NULL,
[DFTIPO] nvarchar(1) NOT NULL,
[DFANO] smallint NOT NULL,
[DFMES] smallint NOT NULL,
[DFCOR] int NOT NULL,
[DFOCUR] smallint NOT NULL,
[DFNIVCOD] nvarchar(20) NULL,
[TARDNIVRES] nvarchar(60) NULL,
[TARDNIVAUT] nvarchar(60) NULL,
[TARESTADO] smallint NULL,
[DFTACCION] nvarchar(30) NULL,
[TARRESUMEN] nvarchar(1000) NULL,
[TAROBSERV] nvarchar(MAX) NULL,
[TARFCHRESP] datetime NULL,
[TARPRIORID] smallint NULL,
[TARCICLICIDAD] smallint NULL,
[TARNRODIAS] smallint NULL,
[TARTIPUSU] smallint NULL,
[TARUSURESP] nvarchar(25) NULL,
[TARTIPDEPEND] smallint NULL,
[TARAUTLECT] smallint NULL,
[TARRESLECT] smallint NULL,
[TARFCHCTRL] datetime NULL,
[TARHRSUTIL] int NULL,
[TARHRSINGRESO] nvarchar(8) NULL,
[TARFCHINGRESO] datetime NULL,
[TARULTRESP] smallint NULL,
[TOTAL_TAREA] int NULL,
[TOTAL_ATRAZADAS] int NULL,
[TOTAL_PENDIENTES] int NULL,
[TOTAL_CUMPLIDAS] int NULL,
[COLORTAREA] int NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[VISTADFTAREAScc] SET (LOCK_ESCALATION = TABLE);
GO
