/****** Object: Table [dbo].[WV_CASILLA]   Script Date: 30-08-2025 18:38:46 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[WV_CASILLA] (
[ID_CASILLA] int NOT NULL,
[SIGLA] char(20) NOT NULL,
[ABREVIATUR] char(40) NOT NULL,
[NOMBRE_CAS] char(120) NOT NULL,
[RESPONSABL] char(120) NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[WV_CASILLA] SET (LOCK_ESCALATION = TABLE);
GO
