/****** Object: Table [dbo].[WV_LISTA]   Script Date: 30-08-2025 18:38:46 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[WV_LISTA] (
[ID_LISTA] int NOT NULL,
[NOMBRE_LIS] char(60) NOT NULL,
[ID_ESTADO] smallint NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[WV_LISTA] SET (LOCK_ESCALATION = TABLE);
GO
