/****** Object: Table [dbo].[WV_LISTA_C]   Script Date: 30-08-2025 18:38:47 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[WV_LISTA_C] (
[ID_LISTA] int NOT NULL,
[ID_CASILLA] int NOT NULL,
[ID_EST_Cas] int NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[WV_LISTA_C] SET (LOCK_ESCALATION = TABLE);
GO
