/****** Object: Table [dbo].[WV_MATERIA]   Script Date: 30-08-2025 18:38:47 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[WV_MATERIA] (
[ID_MATERIA] int NOT NULL,
[MATERIA] char(60) NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[WV_MATERIA] SET (LOCK_ESCALATION = TABLE);
GO
