/****** Object: Table [dbo].[WV_REPARTI]   Script Date: 30-08-2025 18:38:47 ******/
USE [docflowpro];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[WV_REPARTI] (
[ID_REPARTI] int NOT NULL,
[REPARTICIO] char(60) NOT NULL,
[IP_REPARTI] char(60) NOT NULL,
[ACTIVO] smallint NOT NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[WV_REPARTI] SET (LOCK_ESCALATION = TABLE);
GO
