-- Master script to create all tables
-- Generated automatically from sql/all.sql.txt
-- Execute this script to create all database tables

:r tables/Archivos.sql
:r tables/AuditorSistema.sql
:r tables/BandejaEntradaArchivo.sql
:r tables/BandejaEntradaCategoria.sql
:r tables/BandejaEntradaFormato.sql
:r tables/BandejaEntradaVirtual.sql
:r tables/CasillaFacturas.sql
:r tables/CasillaFacturas2.sql
:r tables/DFADJCONTENIDO.sql
:r tables/DFADJUNT.sql
:r tables/DFADJUNT_old.sql
:r tables/DFASIGNAR.sql
:r tables/DFAVIDETAL.sql
:r tables/DFAVISO.sql
:r tables/DFAYUDAS.sql
:r tables/DFBusquedaGrillaDocumentos.sql
:r tables/DFCARPET.sql
:r tables/DFCATEGORIA.sql
:r tables/DFCATEGORIA_OLD.sql
:r tables/DFCODBAR.sql
:r tables/DFCONAUTORIZADO.sql
:r tables/DFCONTENIDO.sql
:r tables/DFDOCASO.sql
:r tables/DFDOCDIGITALANEXOS.sql
:r tables/DFDOCEXT.sql
:r tables/DFDOCGUID.sql
:r tables/DFDOCSERIE.sql
:r tables/DFDOCUM.sql
:r tables/DFDOCUMDOCDIGITAL.sql
:r tables/DFEDIFIC.sql
:r tables/DFEDITORMENSAJES.sql
:r tables/DFEINGRE.sql
:r tables/DFENVIO_EMAIL.sql
:r tables/DFESTADODOC.sql
:r tables/DFFormaEnvios.sql
:r tables/DFHISCAR.sql
:r tables/DFHISDOC.sql
:r tables/DFHISINT.sql
:r tables/DFHISMSG.sql
:r tables/DFHISTORIAACCION.sql
:r tables/DFIENVIO.sql
:r tables/DFIMAGEN.sql
:r tables/DFIMAGEN_old.sql
:r tables/DFMAIL.sql
:r tables/DFMAILOUT.sql
:r tables/DFMAILold.sql
:r tables/DFMOV.sql
:r tables/DFMSGTEM.sql
:r tables/DFMailDoc.sql
:r tables/DFNOTIFICADOR.sql
:r tables/DFOBING.sql
:r tables/DFOPNOTIFICADOR.sql
:r tables/DFREMPAS.sql
:r tables/DFRENVIO.sql
:r tables/DFRESPUESTAZONA.sql
:r tables/DFRESPUETAZONAL.sql
:r tables/DFRESTAR.sql
:r tables/DFRFAROS.sql
:r tables/DFRREFER.sql
:r tables/DFSELECUSU.sql
:r tables/DFSESION.sql
:r tables/DFSeries.sql
:r tables/DFTAREAS.sql
:r tables/DFTAREASDOC.sql
:r tables/DFTEXTO.sql
:r tables/DFTareaZonales.sql
:r tables/DFUSUAUTORIZADOS.sql
:r tables/EDD_ARCHIVOS.sql
:r tables/EDD_FIRMAS.sql
:r tables/EDD_PLANTILLAS.sql
:r tables/EDD_SEFORPLA.sql
:r tables/EDD_VISACIONES.sql
:r tables/EDN_CLASIFICACION.sql
:r tables/EDN_DESTINATARIO.sql
:r tables/EDN_FARO.sql
:r tables/EDN_MENSAJE.sql
:r tables/EDN_ORIGINADOR.sql
:r tables/EDN_PREFIJO.sql
:r tables/EDN_TIPO.sql
:r tables/EDN_XMT.sql
:r tables/FACTURASTMP.sql
:r tables/FACTURAXMLPDF.sql
:r tables/F_DOC.sql
:r tables/Files.sql
:r tables/Files_old.sql
:r tables/HistoriaPublica.sql
:r tables/ListadoSistemas.sql
:r tables/RegistroApp.sql
:r tables/ResponsableTMP.sql
:r tables/SECATALO.sql
:r tables/SECATEGORIAS.sql
:r tables/SECLASEG.sql
:r tables/SECORFOR.sql
:r tables/SECORFORDOCTIPNIV.sql
:r tables/SEConfiguracion.sql
:r tables/SEConfiguracion_old.sql
:r tables/SEDEFIMP.sql
:r tables/SEEMAIL.sql
:r tables/SEFORDOC.sql
:r tables/SEFORDOCDOCDIGITAL.sql
:r tables/SEFORDOCNIV.sql
:r tables/SEFORDOCSII.sql
:r tables/SEFORPLA.sql
:r tables/SEFORPLADATOS.sql
:r tables/SEFORPLAHTML.sql
:r tables/SEFORPLAMEDIDAS.sql
:r tables/SEFORSII.sql
:r tables/SELISTIP.sql
:r tables/SELOG.sql
:r tables/SEMODULO.sql
:r tables/SENIVDES.sql
:r tables/SENIVEL.sql
:r tables/SEOPUSSI.sql
:r tables/SEORGDEP.sql
:r tables/SEPARAME.sql
:r tables/SEPERMIS.sql
:r tables/SEPERSONAL.sql
:r tables/SEREM.sql
:r tables/SEREMTIP.sql
:r tables/SERESNUM.sql
:r tables/SESUBCATEGORIAS.sql
:r tables/SETIPTAR.sql
:r tables/SEUSUARI.sql
:r tables/SEUSUFIRMA.sql
:r tables/SEUSUFIRMADOR.sql
:r tables/SEUSUPERFIL.sql
:r tables/SEUSUSIS.sql
:r tables/SGP_Serials.sql
:r tables/SeFormaEnvio.sql
:r tables/TMPADJUNTOS.sql
:r tables/TMPDFDOCUM.sql
:r tables/TMPDFSELECCION.sql
:r tables/TMPENVIO.sql
:r tables/TMPImagen.sql
:r tables/TMPOBSERVACION.sql
:r tables/TMPREFERENCIAS.sql
:r tables/TMPTAREAS.sql
:r tables/TX_TMPEDITOR.sql
:r tables/VISTADFTAREAScc.sql
:r tables/WV_CASILLA.sql
:r tables/WV_LISTA.sql
:r tables/WV_LISTA_C.sql
:r tables/WV_MATERIA.sql
:r tables/WV_REPARTI.sql
:r tables/bandeja.sql
:r tables/expcompartir.sql
:r tables/expdocref.sql
:r tables/expedientes.sql
:r tables/exphistoria.sql
:r tables/exphitos.sql
:r tables/explistachequeo.sql
:r tables/expobservacion.sql
:r tables/expreferencias.sql
